version: '3.4'
x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.2
    environment:
      discovery.type: "single-node"
      cluster.name: contextElasticSearch
    volumes:
      - ./data/elasticsearch/:/usr/share/elasticsearch/data
    logging: *default-logging
    restart: always
    ports:
      - 9200:9200
      - 9300:9300
  unomi:
    image: apache/unomi:1.5.0-SNAPSHOT
    environment:
      - UNOMI_ELASTICSEARCH_ADDRESSES:elasticsearch:9200
    volumes:
      - ./data/elasticsearch/:/usr/share/elasticsearch/data
    logging: *default-logging
    restart: always
    ports:
      - 8181:8181
      - 9443:9443
      - 8102:8102