version: '3.4'
x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"
services:
  n8n:
    image: n8nio/n8n
    restart: always
    domainname: n8n
    ports:
      - "127.0.0.1:5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER
      - N8N_BASIC_AUTH_PASSWORD
      - N8N_HOST=${DOMAIN_NAME}
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - NODE_ENV=production
      - WEBHOOK_TUNNEL_URL=http://${DOMAIN_NAME}/
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
    volumes:
      - ${DATA_FOLDER}/.n8n:/home/node/.n8n
    extra_hosts:
      - "n8n_mautic.docker.localhost:host-gateway"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.2
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "cluster.name=contextElasticSearch"
    volumes:
      - ./data/elasticsearch/:/usr/share/elasticsearch/data
    logging: *default-logging
    restart: always
    ports:
      - 9200:9200
      - 9300:9300
  unomi:
    image: apache/unomi:1.5.7-SNAPSHOT
    environment:
      - UNOMI_ELASTICSEARCH_ADDRESSES=elasticsearch:9200
    volumes:
      - ./data/elasticsearch/:/usr/share/elasticsearch/data
    logging: *default-logging
    restart: always
    ports:
      - 8181:8181
      - 9443:9443
      - 8102:8102
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
#   extra_hosts:
#     - "localhost:host-gateway"
#  kibana:
#    image: docker.elastic.co/kibana/kibana:7.4.2
#    container_name: kib01
#    ports:
#      - 5601:5601
#    environment:
#      ELASTICSEARCH_URL: http://elasticsearch:9200
#      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
#    links:
#      - elasticsearch
#    depends_on:
#      - elasticsearch
