version: '3.4'
x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.2
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "cluster.name=contextElasticSearch"
    volumes:
      - ./data/elasticsearch/:/usr/share/elasticsearch/data
    logging: *default-logging
    restart: always
    ports:
      - 9200:9200
      - 9300:9300
  unomi:
    image: apache/unomi:1.5.7-SNAPSHOT
    environment:
      - UNOMI_ELASTICSEARCH_ADDRESSES=elasticsearch:9200
    volumes:
      - ./data/elasticsearch/:/usr/share/elasticsearch/data
    logging: *default-logging
    restart: always
    ports:
      - 8181:8181
      - 9443:9443
      - 8102:8102
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
#   extra_hosts:
#     - "localhost:host-gateway"
#  kibana:
#    image: docker.elastic.co/kibana/kibana:7.4.2
#    container_name: kib01
#    ports:
#      - 5601:5601
#    environment:
#      ELASTICSEARCH_URL: http://elasticsearch:9200
#      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
#    links:
#      - elasticsearch
#    depends_on:
#      - elasticsearch
